Repository krayin/laravel-crm, pull requests merged in 2022-09, with the labels that each got.

#1067 Fixed #802
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/datagrid/table.vue
Labels: Getting Fixed

#1069 Issue #537 fixed
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/js/admin.js.LICENSE.txt
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/js/app.js
Labels: Getting Fixed

#1082 Fixed #1063
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/date-range.vue
Labels: Getting Fixed

#1072 Fixed #821
  packages/Webkul/Admin/src/DataGrids/Setting/AttributeDataGrid.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Traits/ProvideDropdownOptions.php
Labels: Getting Fixed

#1090 Fixed #792
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
  packages/Webkul/UI/src/Resources/assets/js/components/tabs/tabs.vue
Labels: Getting Fixed

#1068 Fixed #764
  packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/UI/publishable/assets/images/controls.svg
  packages/Webkul/UI/publishable/assets/images/favicon.ico
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/datagrid/side-filter.vue
Labels: conflicts

#1092 Fixed #435
  packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
Labels: Getting Fixed

#1039 Enhancement #974 done
  packages/Webkul/WebForm/src/Resources/lang/ar/app.php
  packages/Webkul/WebForm/src/Resources/lang/en/app.php
  packages/Webkul/WebForm/src/Resources/lang/tr/app.php
  packages/Webkul/WebForm/src/Resources/views/settings/web-forms/edit.blade.php
Labels: Getting Fixed

#1074 Issue #1071 fixed
  packages/Webkul/Admin/src/Http/Middleware/Bouncer.php
Labels: review request

#1089 Fixed #1087
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/datagrid/filters.vue
Labels: Getting Fixed

#1081 Issue #1073 fixed
  packages/Webkul/Admin/src/Helpers/Dashboard.php
  packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
Labels: Getting Fixed

#1096 Issue #847 fixed
  packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js.blade.php
  packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js/form.blade.php
Labels: Getting Fixed

#1097 Fixed #1091
  packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
Labels: Hold, In Testing

#1101 Issue #1088 Fixed
  packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
Labels: In Testing

#1102 Issue #816 Fixed
  docker/8.2/Dockerfile
  docker/8.2/php.ini
  docker/8.2/start-container
  docker/8.2/supervisord.conf
  packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
Labels: Approved

#1080 Fix for issue #374
  packages/Webkul/Email/src/Repositories/AttachmentRepository.php
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/attachment/attachment-item.vue
  packages/Webkul/UI/src/Resources/assets/js/components/attachment/attachment-wrapper.vue
Labels: change request

#1103 Issue #663 fixed
  composer.json
  config/app.php
  packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php
  packages/Webkul/Admin/src/Http/Controllers/Quote/QuoteController.php
  packages/Webkul/UI/src/Resources/lang/en/app.php
Labels: Approved

#1104 Fixed #1008
  .env.example
  config/mail.php
  packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php
  packages/Webkul/Email/src/Mails/Email.php
Labels: Approved

#1107 Changelog-Updated
  CHANGELOG for v1.x.x.md
Labels: review request

#1108 Fixed #947
  packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
  packages/Webkul/Workflow/src/Helpers/Entity/Lead.php
Labels: Approved
