Repository krayin/laravel-crm, pull requests merged in 2024-06, with the labels that each got.

#1243 fixed #1240
  packages/Webkul/Admin/src/Resources/views/quotes/pdf.blade.php
Labels: Approved

#1232 Fixed #1172
  packages/Webkul/WebForm/publishable/assets/css/web-form.css
  packages/Webkul/WebForm/publishable/assets/js/web-form.js
  packages/Webkul/WebForm/publishable/assets/js/web-form.js.LICENSE.txt
  packages/Webkul/WebForm/publishable/assets/mix-manifest.json
  packages/Webkul/WebForm/src/Resources/assets/sass/web-form.scss
  packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js/form.blade.php
Labels: Approved

#1227 Fixed #1215
  composer.lock
Labels: Approved

#1151 feature: Spanish language support
  config/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/UI/src/Resources/lang/es/app.php
  packages/Webkul/WebForm/src/Resources/lang/es/app.php
Labels: Approved

#1157 Delete phpinfo
  public/phpinfo.php
Labels: In Testing

#1114 Fixed #1113
  packages/Webkul/Admin/src/Exceptions/Handler.php
Labels: In Testing

#1158 Persian translation
  config/app.php
  packages/Webkul/Admin/src/Resources/assets/sass/rtl.scss
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
  packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
  packages/Webkul/UI/src/Resources/lang/fa/app.php
  packages/Webkul/WebForm/src/Resources/lang/fa/app.php
Labels: In Testing

#1235 Fixed #1220
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/datagrid/side-filter.vue
Labels: Bug Fixed

#1231 Fixed #1190
  packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
Labels: Bug Fixed

#1127 issue #1123 fixed
  packages/Webkul/WebForm/src/Http/routes.php
Labels: Bug Fixed

#1253 Issue #1242 fixed.
  packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
  packages/Webkul/UI/publishable/assets/js/ui.js
  packages/Webkul/UI/publishable/assets/mix-manifest.json
  packages/Webkul/UI/src/Resources/assets/js/components/date-range-basic.vue
Labels: Changes Request

#1230 Fixed #1222
  packages/Webkul/Attribute/src/Repositories/AttributeValueRepository.php
Labels: Changes Request

#1256 Issue #1198 fixed.
  packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php
  packages/Webkul/Email/src/Repositories/EmailRepository.php
Labels: Discussion
